### PR TITLE
Fix parsing of PCI domains longer than 4 digits

### LINKED ISSUE #372: error parsing pci address
Seeing error `error parsing the pci address "10001:80:05.0"`

As far as I can see, it looks like Intel VMD (virtual RAID) devices - `lspci` output:
```
10001:80:05.0 PCI bridge: Intel Corporation Device 352c (rev 04)
10001:80:07.0 PCI bridge: Intel Corporation Device 352d (rev 04)
10001:8a:00.0 Non-Volatile memory controller: Micron Technology Inc 7450 PRO NVMe SSD (rev 01)
10001:8b:00.0 Non-Volatile memory controller: Micron Technology Inc 7450 PRO NVMe SSD (rev 01)
10002:80:01.0 PCI bridge: Intel Corporation Device 352a (rev 04)
10002:80:03.0 PCI bridge: Intel Corporation Device 352b (rev 04)
10002:80:05.0 PCI bridge: Intel Corporation Device 352c (rev 04)
10002:80:07.0 PCI bridge: Intel Corporation Device 352d (rev 04)
10002:8a:00.0 Non-Volatile memory controller: Micron Technology Inc 7450 PRO NVMe SSD (rev 01)
10002:8b:00.0 Non-Volatile memory controller: Micron Technology Inc 7450 PRO NVMe SSD (rev 01)
10002:8c:00.0 Non-Volatile memory controller: Micron Technology Inc 7450 PRO NVMe SSD (rev 01)
10002:8d:00.0 Non-Volatile memory controller: Micron Technology Inc 7450 PRO NVMe SSD (rev 01)
10003:00:05.0 PCI bridge: Intel Corporation Device 352c (rev 04)
10003:00:07.0 PCI bridge: Intel Corporation Device 352d (rev 04)
10004:00:01.0 PCI bridge: Intel Corporation Device 352a (rev 04)
10004:00:03.0 PCI bridge: Intel Corporation Device 352b (rev 04)
10004:00:05.0 PCI bridge: Intel Corporation Device 352c (rev 04)
10004:00:07.0 PCI bridge: Intel Corporation Device 352d (rev 04)
```

### PR DESCRIPTION
**Pull request by ianb-mp**
Allow parsing of PCI addresses like `10001:80:05.0` where the domain component is longer than 4 digits.

The domain component should be able to handle values up to 32 bits - see: https://patches.dpdk.org/project/dpdk/patch/20200512133057.106374-1-dariusz.stojaczyk@intel.com/

Fixes #372

### CODE REVIEW

File: pkg/pci/address/address.go [hunk 1]
```diff
@@ -13,7 +13,7 @@ import (
 
 var (
 	regexAddress *regexp.Regexp = regexp.MustCompile(
-		`^(([0-9a-f]{0,4}):)?([0-9a-f]{2}):([0-9a-f]{2})\.([0-9a-f]{1})$`,
+		`^(([0-9a-f]{0,8}):)?([0-9a-f]{2}):([0-9a-f]{2})\.([0-9a-f]{1})$`,
```
Comment (jaypipes) [inline pkg/pci/address/address.go:16]: @ianb-mp OK, so to be fully compliant with the PCI-X spec, I believe this needs to be:

```
^(1?)(([0-9a-f]{0,4}):)?([0-9a-f]{2}):([0-9a-f]{2})\.([0-9a-f]{1})$
```

Because, according to my research, the domain part of the PCI address is 4 hexadigits *OR* a `1` followed by 4 hexadigits (for the cases where the PCI extension configuration space is used)

Comment (ianb-mp) [reply pkg/pci/address/address.go]: ok, I've pushed another commit with that change however moved the `1?` inside the existing capture group. I also added a test.

**Review by jaypipes — APPROVED** [review]
Awesome, thank you @ianb-mp !
