### PR TITLE
Fix #339 by getting the physical disk info which properly shows SSD vs HDD

### LINKED ISSUE #339: HDD is classified as SSD on windows 10
I was trying out the lib on windows 10 and was surprised to see that it was misclassifying my HDD as an SSD.  Turns out the currently logic just says all "fixed" media types are SSD, which is incorrect.  The "fixed" media type simply means the disk is internal to the PC, so its not "removable" media for example like a USB drive.  I have what I believe to be the correct code (working for me locally) that I will create a PR for.

### PR DESCRIPTION
**Pull request by williambrode**
Fixes #339

### CODE REVIEW

File: pkg/block/block.go [hunk 1]
```diff
@@ -32,6 +32,29 @@ const (
...
+		return DRIVE_TYPE_UNKNOWN
+	case PHYSICAL_DISK_TYPE_HDD:
+		return DRIVE_TYPE_HDD
+	case PHYSICAL_DISK_TYPE_SSD:
+		return DRIVE_TYPE_SSD
+	case PHYSICAL_DISK_TYPE_SCM:
+		return DRIVE_TYPE_UNKNOWN
+	}
+	return DRIVE_TYPE_UNKNOWN
+}
```
Comment (jaypipes) [inline pkg/block/block.go:56]: can we move this into `pkg/block/block_windows.go` please, since it's Windows-specific? Also, let's name this `physicalDiskMediaType` (unexported) to denote that it's the WMI physical disk media type code.

Comment (williambrode) [reply pkg/block/block.go:56]: Ah yeah, I had it there before and then moved it for some reason... will move it back.

**Review by jaypipes — APPROVED** [review]
Awesome, thank you @williambrode! :)

**Comment by jaypipes** [comment]
@williambrode I think a rebase might be needed here.

**Review by jaypipes — APPROVED** [review]
